# Name of the workflow
name: Learn Workflow

# Events that trigger this workflow
on:
  push:
    branches: [main]

# Jobs to run
jobs:
  setup-django-project:  # Fixed: removed space, used hyphen instead
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]
    
    # Steps to execute in this job
    steps:
      - name: Checkout code
        uses: actions/checkout@v6  # Changed to v4 (v6 might not exist yet)
      
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6  # Changed to v4
        with:
          python-version: ${{ matrix.python-version }}  # Added space after colon
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run tests
        run: python manage.py test